version: 2
jobs:
  test:
    docker:
    - image: circleci/golang:1.11
      environment:
        GO111MODULE: "on"
      steps:
      - checkout

      - restore_cache:
        key: go-mod-v1-{{ checksum "go.sum" }}

      - run:
          name: Install Dependencies
          command: "go mod download"

      - save_cache:
          key: go-mod-v1-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - run:
          name: Test
          command: "go test -v -race ./..."

      - run:
          name: Lint Code
          environment:
            GO111MODULE: "off"
          command: |
            go get github.com/golangci/golangci-lint/cmd/golangci-lint
            golangci-lint run

      - run:
          name: Build Project Binary
          command: "go build cmd/robot/main.go"
  build:
    docker:
    - image: circleci/golang:1.11
      environment:
        GO111MODULE: "off"
        USER_NAME: "Ali Shanaakh"
        USER_EMAIL: "github@shanaakh.pro"
      steps:
      - checkout

      - run:
          name: "Set Git Configuration"
          command: |
            git config --global user.name "${USER_NAME}"
            git config --global user.email "${USER_EMAIL}"

      - run:
          name: "Bump Version"
          command: |
            go get github.com/Clever/gitsem
            gitsem -m "[ci skip] Bump version to %s" patch

      - run:
          name: "Release Version"
          command: |
            git remote add authenticated-origin https://${GITHUB_USER}:$GITHUB_API_KEY@github.com/${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}
            git push origin HEAD:${CIRCLE_BRANCH}
